version: '2'

services:
  es:
    container_name: es
    build: es
    ports:
     - "9200:9200"
     - "9300:9300"

  kibana:
    build: kibana
    container_name: kibana
    ports:
     - "5601:5601"
    environment:
     - ELASTICSEARCH_URL=http://es:9200
    links:
     - es:elasticsearch

  packetbeat:
    build: packetbeat
    container_name: packetbeat
    command: ./packetbeat -e -c=packetbeat.yml
    networks:
     - "host"

  test:
    image: phusion/baseimage
    command: bash -c "apt-get update"
