version: '2'

services:
  elasticsearch:
    container_name: elasticsearch
    build: es
    ports:
     - "9200:9200"
     - "9300:9300"

  kibana:
    build: kibana
    container_name: kibana
    ports:
     - "5601:5601"
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200

  packetbeat:
    build: packetbeat
    container_name: packetbeat
    command: # >
#      /bin/bash -c "
#          echo Waiting for Kibana to become ready ...
#          while ! curl -s http://kibana:5601 &>/dev/null; do sleep 3;done;
#          echo Kibana is ready : http://localhost:5601
#          echo Starting Packetbeat : ./packetbeat -e -c=packetbeat.yml
          ./packetbeat -e -c=packetbeat.yml
#      "
    network_mode: host

  test:
    image: phusion/baseimage
    command: bash -c "apt-get update"
